POST http://localhost:5000/api/products
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYwZTY1ZmIyZTRkNjdhNjc4NDg0NWFkNCIsImlhdCI6MTYyNTcxMDcxNH0.8_EtAIfFSVVh7JzFKJkf2Xuj24Llg0M53P_oT7mS37s

{
  "name": "Macarons 6",
  "description": "Sabores: Café, Chocolate, Tangerina, Maracujá, Maçã verde, Pistache, Caramelo com flor de sal e Lemon curd. Valor pela unidade. Acima de 40 unidades - R$4,00 cada",
  "category": "Categoria 1",
  "image": "/images",
  "price": 4.70,
  "countInStock": 10,
  "isFeatured": true
}