POST http://localhost:5000/api/products
content-type: application/json

{
  "name": "Macarons 2",
  "description": "Sabores: Café, Chocolate, Tangerina, Maracujá, Maçã verde, Pistache, Caramelo com flor de sal e Lemon curd. Valor pela unidade. Acima de 40 unidades - R$4,00 cada",
  "category": "Categoria 1",
  "price": 4.70,
  "countInStock": 10,
  "isFeatured": true
}