PUT http://localhost:5000/api/auth/profile
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYwZTY3MzZkYzVlM2ZlNmJlODcwYzQxNCIsImlhdCI6MTYyNTc1NDQ1NSwiZXhwIjoxNjI4MzQ2NDU1fQ.S3ICEyxbP5-arZ3i4XIa2MvJ5b8t4FgoPFX0iRSVSvk
Content-Type: application/json

{
  "givenName": "Roberta",
  "surname": "Robs",
  "email": "maisaa@maisa.com"
}
