PUT http://localhost:5000/api/auth/updatepassword
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYwZTcxMDE0ZTgzODNiN2FiMzAzMTdiYyIsImlhdCI6MTYyNTc1NTY2OCwiZXhwIjoxNjI4MzQ3NjY4fQ.6D02wmTZ5K1uLiz0zU8tuK20arNhXvIoxV9yVpbxeAk
Content-Type: application/json

{
  "currentPassword": "12345678910",
  "newPassword": "12345678"
}
